ERROR - 2020-10-28 16:13:32,813 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:13:34,092 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:13:35,175 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:13:36,200 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:13:36,998 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:14:52,391 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:14:53,650 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:14:54,760 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:14:55,812 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:14:57,139 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:35] - -------------------------------------------------
ERROR - 2020-10-28 16:19:45,130 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 16:19:46,344 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 16:19:47,438 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 16:19:48,432 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 16:19:49,278 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:18:03,870 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:18:05,092 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:18:06,180 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:18:07,170 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:18:09,319 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:19:00,439 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:19:01,245 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:19:02,404 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:19:03,411 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 18:19:04,273 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:16:24,377 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:16:25,479 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:16:26,329 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:16:28,802 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:16:30,555 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:24:30,104 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:24:30,825 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:24:31,911 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:24:32,966 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:24:33,885 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:25:13,115 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:25:15,486 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:25:16,676 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:25:17,917 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:25:20,064 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:26:45,347 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:26:47,711 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:26:48,938 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:26:50,045 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:26:52,221 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:27:47,853 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:27:50,190 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:27:51,238 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:27:52,396 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:27:54,548 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:29:09,456 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:29:13,252 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:29:16,160 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:29:17,384 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:29:19,588 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:31:12,142 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:31:13,931 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:31:14,730 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:31:15,820 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:31:17,580 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:32:20,564 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:32:22,350 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:32:23,870 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:32:25,766 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:32:27,449 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:36:35,067 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:36:36,019 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:36:36,747 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:36:37,553 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-28 23:36:39,208 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:36] - -------------------------------------------------
ERROR - 2020-10-29 01:09:04,813 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:74] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2020-10-29 01:09:08,611 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:74] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2020-10-29 01:27:31,635 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:74] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2020-10-29 01:27:37,080 - D:\Pycharm\AutoProject\SeleniumAutoProject\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:74] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2020-10-29 12:44:00,264 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:75] - 出现异常
ERROR - 2020-10-29 12:44:00,264 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:76] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2020-10-29 12:44:05,970 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:75] - 出现异常
ERROR - 2020-10-29 12:44:05,970 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:76] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2020-10-29 12:44:08,474 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:75] - 出现异常
ERROR - 2020-10-29 12:44:08,474 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:76] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2020-11-16 11:18:12,872 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:76] - 出现异常
ERROR - 2020-11-16 11:18:12,875 - D:\csv\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:77] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-06 13:33:11,650 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - 出现异常
ERROR - 2021-01-06 13:33:11,650 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:81] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-06 14:17:48,620 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-06 14:17:48,620 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-06 20:18:57,629 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-06 20:18:57,629 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-06 20:18:59,909 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-06 20:18:59,909 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-07 09:17:02,923 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:17:02,924 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'AttributeError'>
ERROR - 2021-01-07 09:17:04,055 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:17:04,056 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'AttributeError'>
ERROR - 2021-01-07 09:17:05,041 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:17:05,041 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'AttributeError'>
ERROR - 2021-01-07 09:17:06,101 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:17:06,101 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'AttributeError'>
ERROR - 2021-01-07 09:17:07,120 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:17:07,120 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'AttributeError'>
ERROR - 2021-01-07 09:20:12,063 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:20:12,064 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'AssertionError'>
ERROR - 2021-01-07 09:20:15,736 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:20:15,736 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-07 09:20:17,608 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:20:17,609 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'AssertionError'>
ERROR - 2021-01-07 09:20:20,103 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:79] - 出现异常
ERROR - 2021-01-07 09:20:20,103 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:80] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-07 09:34:32,803 - D:/se/Se_Project/Util/log.py - log.py[:44] - 测试error
CRITICAL - 2021-01-07 09:34:32,803 - D:/se/Se_Project/Util/log.py - log.py[:47] - 测试critical
ERROR - 2021-01-07 09:36:40,131 - D:/se/Se_Project/Util/log.py - log.py[:45] - 测试error
CRITICAL - 2021-01-07 09:36:40,131 - D:/se/Se_Project/Util/log.py - log.py[:48] - 测试critical
ERROR - 2021-01-07 10:06:43,762 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:83] - 出现异常
ERROR - 2021-01-07 10:06:43,763 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:84] - <class 'AssertionError'>
ERROR - 2021-01-07 10:06:49,560 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:83] - 出现异常
ERROR - 2021-01-07 10:06:49,560 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:84] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-07 10:06:52,170 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:83] - 出现异常
ERROR - 2021-01-07 10:06:52,170 - D:\se\Se_Project\Testcases\loginPageTest\test_publciLoginPage.py - test_publciLoginPage.py[:84] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-07 10:21:33,209 - D:\se\Se_Project\Util\log.py - log.py[:46] - 出现异常
ERROR - 2021-01-07 10:21:33,209 - D:\se\Se_Project\Util\log.py - log.py[:46] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-07 10:21:39,421 - D:\se\Se_Project\Util\log.py - log.py[:46] - 出现异常
ERROR - 2021-01-07 10:21:39,421 - D:\se\Se_Project\Util\log.py - log.py[:46] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-07 10:21:42,297 - D:\se\Se_Project\Util\log.py - log.py[:46] - 出现异常
ERROR - 2021-01-07 10:21:42,298 - D:\se\Se_Project\Util\log.py - log.py[:46] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-07 10:25:51,024 - D:\se\Se_Project\Util\log.py - log.py[:46] - 出现异常
ERROR - 2021-01-07 10:25:51,024 - D:\se\Se_Project\Util\log.py - log.py[:46] - <class 'selenium.common.exceptions.TimeoutException'>
ERROR - 2021-01-19 15:05:29,570 - D:\se\Se_Project\Util\log.py - log.py[:46] - Exception: Don't find Boe, please check config
ERROR - 2021-01-19 15:07:20,198 - D:\se\Se_Project\Util\log.py - log.py[:46] - Exception: Don't find Boe, please check config
ERROR - 2021-01-19 15:22:37,643 - D:\se\Se_Project\Util\log.py - log.py[:46] - Exception: Don't find Boe, please check config
ERROR - 2021-01-19 15:23:30,747 - D:\se\Se_Project\Util\log.py - log.py[:46] - Exception: Don't find Boe, please check config
ERROR - 2021-01-19 17:42:41,544 - D:\se\Se_Project\Util\log.py - log.py[:46] - 没有找到对应配置项，请检查配置
ERROR - 2021-01-19 17:43:40,309 - D:\se\Se_Project\Util\log.py - log.py[:46] - 没有找到对应配置项，请检查配置
ERROR - 2021-01-19 20:46:13,141 - D:\se\Se_Project\Util\log.py - log.py[:46] - 没有找到对应配置项，请检查配置
ERROR - 2021-01-19 20:47:05,598 - D:\se\Se_Project\Util\log.py - log.py[:46] - 没有找到对应配置项，请检查配置
ERROR - 2021-01-19 21:00:53,801 - D:\se\Se_Project\Util\log.py - log.py[:46] - 没有找到对应配置项，请检查配置
